### PR TITLE
Github workflow to automatically build Docker images

### PR DESCRIPTION
**Pull request by 3nids**
This workflows compares the available tags on Docker hub with the last available ubuntu packages and determines what to update (and does it).

To push, we need to add the login user and pass as secrets to the workflow

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@pslh can you have a look with @3nids for secrets and so?

**Comment by 3nids** [comment]
Someone needs to setup the [github secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets):
* docker_username
* docker_password

**Comment by pslh** [comment]
I have added two github secrets

**Comment by mbernasocchi** [comment]
🤩

**Comment by 3nids** [comment]
it worked :)
https://hub.docker.com/r/openquake/qgis-server/tags

**Pull request merged**
