### PR TITLE
Enable wfs3

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Review by daniviga — APPROVED** [review]
LGTM, thanks!

**Comment by m-kuhn** [comment]
Thanks for merging @daniviga 

@faebebin tested this on Friday and mentioned some issues with the webinterface, even though individual requests work. If you have a precise description, can you add that here, @faebebin? Thanks

**Comment by daniviga** [comment]
Let me know if I can help, BTW there's any specific reason why you'd like to have a new endpoint for wfs3 instead of relying on the existing ogc one?

**Comment by m-kuhn** [comment]
If I understood it correctly, this path is hardcoded into QGIS (CC @mbernasocchi )

**Comment by daniviga** [comment]
Doing this means that everything after `/wfs3/` will be passed to `/qgis/qgis_mapserv.fcgi` e.g.

`/wfs3/?SERVICE=WMS&VERSION=1.3.0` -> `/qgis/qgis_mapserv.fcgi?SERVICE=WMS&VERSION=1.3.0`

If it is expected that QGIS takes `/wfs3/` directly this is not going to work

**Comment by faebebin** [comment]
I currently solved it like this, for not having to pass `?map=/path/to/proj.qgs` but rather can request `wfs3/<poj-name>/uri/rest/etc`
```
        location /ogc/wfs3/ {
            rewrite ^/ogc/wfs3/([^/]*)/(.*)$ /qgis/qgis_mapserv.fcgi/wfs3/$2?map=/io/data/$1/$1.qgs;
        }
```

But this means you have to specify the <proj-name>.

**Pull request merged**
